# Generated by Django 5.2.1 on 2025-05-16 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_proof_type', models.CharField(blank=True, choices=[('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('NATIONAL_ID', 'National ID'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('id_proof_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_proof_file', models.FileField(blank=True, null=True, upload_to='customers/id_proofs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['full_name'],
            },
        ),
    ]
