# Generated by Django 5.2.1 on 2025-05-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carriers', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('iccid_number', models.CharField(max_length=20)),
                ('imsi_number', models.CharField(blank=True, max_length=25, null=True)),
                ('basket_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sim_status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Blocked', 'Blocked'), ('SUSPEND', 'Suspend')], default='Available', max_length=20)),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sim_type', models.CharField(choices=[('Airtel', 'Airtel'), ('idea', 'Idea'), ('Jio', 'Jio'), ('BSNL', 'BSNL'), ('Other', 'Other')], default='Other', max_length=20)),
                ('imei_number', models.CharField(blank=True, max_length=20, null=True)),
                ('current_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('new_sim_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('remark1', models.TextField(blank=True, null=True)),
                ('remark2', models.TextField(blank=True, null=True)),
                ('remark3', models.TextField(blank=True, null=True)),
                ('vehicle_reg_no', models.CharField(blank=True, max_length=20, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_company', models.CharField(blank=True, max_length=100, null=True)),
                ('starting_odo_meter', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simcards', to='carriers.carrier')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simcards', to='departments.department')),
            ],
            options={
                'verbose_name': 'SIM Card',
                'verbose_name_plural': 'SIM Cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
