# Generated by Django 5.2.1 on 2025-05-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcard',
            name='iccid_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
