# Generated by Django 5.2.1 on 2025-05-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcards', '0002_alter_simcard_iccid_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcard',
            name='sim_type',
            field=models.CharField(choices=[('Airtel', 'Airtel'), ('Idea', 'Idea'), ('Jio', 'Jio'), ('BSNL', 'BSNL'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
