# Generated by Django 5.2.1 on 2025-06-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcards', '0003_alter_simcard_sim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcard',
            name='sim_status',
            field=models.CharField(choices=[('Available', 'Available'), ('DISABLE', 'Disable'), ('ACTIVE', 'Active'), ('DEACTIVE', 'Deactive'), ('IDLE', 'Idle'), ('Blocked', 'Blocked')], default='Available', max_length=20),
        ),
    ]
