# Generated by Django 5.2.1 on 2025-06-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simcards', '0004_alter_simcard_sim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcard',
            name='sim_status',
            field=models.CharField(choices=[('Available', 'Available'), ('DISABLE', 'Disable'), ('ACTIVE', 'Active'), ('DEACTIVE', 'Deactive'), ('IDLE', 'Idle'), ('Repair', 'Repair'), ('Communication_Lost', 'Communication Lost'), ('GPS_Missing', 'Gps Missing'), ('Temporary_Withdrawal', 'Temporary Withdrawal'), ('Accident', 'Accident'), ('Scrap', 'Scrap'), ('No_Vehicle', 'No Vehicle')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='sim_type',
            field=models.CharField(choices=[('Airtel', 'Airtel'), ('Idea', 'Idea'), ('Jio', 'Jio'), ('BSNL', 'BSNL'), ('Not_Assigned', 'Not_Assigned')], default='Not_Assigned', max_length=20),
        ),
    ]
