# Generated by Django 5.2.1 on 2025-05-31 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchrecord',
            name='device',
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('imei_no', models.CharField(max_length=20)),
                ('person', models.CharField(max_length=100)),
                ('sent_parcel_by', models.CharField(max_length=100)),
                ('collected_by', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
        migrations.DeleteModel(
            name='ReturnRecord',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DispatchRecord',
        ),
    ]
