# Generated by Django 5.2.1 on 2025-05-31 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('stock', '0002_remove_dispatchrecord_device_inventoryitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('parcel_sent_by', models.CharField(blank=True, max_length=100)),
                ('docket_number', models.CharField(blank=True, max_length=100)),
                ('collected_person_name', models.CharField(blank=True, max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
    ]
