# Generated by Django 5.2.1 on 2025-06-24 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_devicedispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedispatch',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='devicedispatch',
            name='imei_no',
            field=models.CharField(default=datetime.date(2025, 6, 24), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicedispatch',
            name='mobile_no',
            field=models.CharField(default=datetime.datetime(2025, 6, 24, 10, 29, 45, 738610, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicedispatch',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicedispatch',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('dispatched', 'Dispatched'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='dispatched', max_length=50),
        ),
        migrations.AddField(
            model_name='devicereturn',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='devicereturn',
            name='imei_no',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicereturn',
            name='mobile_no',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicereturn',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicereturn',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('dispatched', 'Dispatched'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='returned', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('dispatched', 'Dispatched'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicedispatch',
            name='collected_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicedispatch',
            name='docket_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicedispatch',
            name='parcel_sent_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicereturn',
            name='collected_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicereturn',
            name='docket_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicereturn',
            name='parcel_sent_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='imei_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='mobile_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
