# Generated by Django 5.2.1 on 2025-05-30 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_user'),
        ('simcards', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sims', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_assignments', to='customers.customer')),
                ('sim_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='simcards.simcard', to_field='mobile_number')),
            ],
            options={
                'verbose_name': 'SIM Assignment',
                'verbose_name_plural': 'SIM Assignments',
                'ordering': ['-activation_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DEACTIVATED', 'Deactivated'), ('REACTIVATED', 'Reactivated')], max_length=20)),
                ('change_details', models.JSONField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assignments.simassignment')),
            ],
            options={
                'verbose_name': 'Assignment History',
                'verbose_name_plural': 'Assignment Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='simassignment',
            index=models.Index(fields=['activation_date'], name='assignments_activat_d982a0_idx'),
        ),
        migrations.AddIndex(
            model_name='simassignment',
            index=models.Index(fields=['expiry_date'], name='assignments_expiry__67033b_idx'),
        ),
        migrations.AddIndex(
            model_name='simassignment',
            index=models.Index(fields=['is_active'], name='assignments_is_acti_76e4e0_idx'),
        ),
    ]
